// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using TradeControl.Tax.UK.Hmrc.Sa.v1_0.BusinessIncomeSummary.V3.Wire;
//
//    var bissWireResponse = BissWireResponse.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8602
#pragma warning disable CS8603

namespace TradeControl.Tax.UK.Hmrc.Sa.v1_0.BusinessIncomeSummary.V3.Wire
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    public partial class BissWireResponse
    {
        [JsonPropertyName("total")]
        public Total Total { get; set; }

        [JsonPropertyName("profit")]
        public Profit Profit { get; set; }

        [JsonPropertyName("loss")]
        public Loss Loss { get; set; }

        [JsonPropertyName("outstandingBusinessIncome")]
        public double OutstandingBusinessIncome { get; set; }
    }

    public partial class Loss
    {
        [JsonPropertyName("net")]
        public double Net { get; set; }

        [JsonPropertyName("taxable")]
        public double Taxable { get; set; }
    }

    public partial class Profit
    {
        [JsonPropertyName("net")]
        public double Net { get; set; }

        [JsonPropertyName("taxable")]
        public double Taxable { get; set; }

        [JsonPropertyName("adjusted")]
        public double Adjusted { get; set; }
    }

    public partial class Total
    {
        [JsonPropertyName("income")]
        public double Income { get; set; }

        [JsonPropertyName("expenses")]
        public double Expenses { get; set; }

        [JsonPropertyName("additions")]
        public double Additions { get; set; }

        [JsonPropertyName("deductions")]
        public double Deductions { get; set; }

        [JsonPropertyName("accountingAdjustments")]
        public double AccountingAdjustments { get; set; }
    }

    public partial class BissWireResponse
    {
        public static BissWireResponse FromJson(string json) => JsonSerializer.Deserialize<BissWireResponse>(json, TradeControl.Tax.UK.Hmrc.Sa.v1_0.BusinessIncomeSummary.V3.Wire.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this BissWireResponse self) => JsonSerializer.Serialize(self, TradeControl.Tax.UK.Hmrc.Sa.v1_0.BusinessIncomeSummary.V3.Wire.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }
    
    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
                get => _dateTimeStyles;
                set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
                get => _dateTimeFormat ?? string.Empty;
                set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
                get => _culture ?? CultureInfo.CurrentCulture;
                set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
                string text;


                if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                        || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
                {
                        value = value.ToUniversalTime();
                }

                text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

                writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                string? dateText = reader.GetString();

                if (string.IsNullOrEmpty(dateText) == false)
                {
                        if (!string.IsNullOrEmpty(_dateTimeFormat))
                        {
                                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                        }
                        else
                        {
                                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                        }
                }
                else
                {
                        return default(DateTimeOffset);
                }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8602
#pragma warning restore CS8603
