// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using TradeControl.Tax.UK.Hmrc.Sa.v1_0.Calculations.V8.Wire2025;
//
//    var calculationResponse2025 = CalculationResponse2025.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8602
#pragma warning disable CS8603

namespace TradeControl.Tax.UK.Hmrc.Sa.v1_0.Calculations.V8.Wire2025
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    public partial class CalculationResponse2025
    {
        [JsonPropertyName("metadata")]
        public Metadata Metadata { get; set; }

        [JsonPropertyName("inputs")]
        public Inputs Inputs { get; set; }

        [JsonPropertyName("calculation")]
        public Calculation Calculation { get; set; }

        [JsonPropertyName("messages")]
        public Messages Messages { get; set; }
    }

    public partial class Calculation
    {
        [JsonPropertyName("allowancesAndDeductions")]
        public AllowancesAndDeductions AllowancesAndDeductions { get; set; }

        [JsonPropertyName("reliefs")]
        public Reliefs Reliefs { get; set; }

        [JsonPropertyName("taxDeductedAtSource")]
        public Dictionary<string, double> TaxDeductedAtSource { get; set; }

        [JsonPropertyName("giftAid")]
        public GiftAid GiftAid { get; set; }

        [JsonPropertyName("royaltyPayments")]
        public RoyaltyPayments RoyaltyPayments { get; set; }

        [JsonPropertyName("notionalTax")]
        public NotionalTax NotionalTax { get; set; }

        [JsonPropertyName("marriageAllowanceTransferredIn")]
        public MarriageAllowanceTransferredIn MarriageAllowanceTransferredIn { get; set; }

        [JsonPropertyName("pensionContributionReliefs")]
        public PensionContributionReliefs PensionContributionReliefs { get; set; }

        [JsonPropertyName("pensionSavingsTaxCharges")]
        public PensionSavingsTaxCharges PensionSavingsTaxCharges { get; set; }

        [JsonPropertyName("studentLoans")]
        public StudentLoan[] StudentLoans { get; set; }

        [JsonPropertyName("codedOutUnderpayments")]
        public CodedOutUnderpayments CodedOutUnderpayments { get; set; }

        [JsonPropertyName("foreignPropertyIncome")]
        public ForeignPropertyIncome[] ForeignPropertyIncome { get; set; }

        [JsonPropertyName("businessProfitAndLoss")]
        public BusinessProfitAndLoss[] BusinessProfitAndLoss { get; set; }

        [JsonPropertyName("employmentAndPensionsIncome")]
        public EmploymentAndPensionsIncome EmploymentAndPensionsIncome { get; set; }

        [JsonPropertyName("employmentExpenses")]
        public EmploymentExpenses EmploymentExpenses { get; set; }

        [JsonPropertyName("seafarersDeductions")]
        public SeafarersDeductions SeafarersDeductions { get; set; }

        [JsonPropertyName("foreignTaxForFtcrNotClaimed")]
        public ForeignTaxForFtcrNotClaimed ForeignTaxForFtcrNotClaimed { get; set; }

        [JsonPropertyName("stateBenefitsIncome")]
        public StateBenefitsIncome StateBenefitsIncome { get; set; }

        [JsonPropertyName("shareSchemesIncome")]
        public ShareSchemesIncome ShareSchemesIncome { get; set; }

        [JsonPropertyName("foreignIncome")]
        public ForeignIncome ForeignIncome { get; set; }

        [JsonPropertyName("chargeableEventGainsIncome")]
        public ChargeableEventGainsIncome ChargeableEventGainsIncome { get; set; }

        [JsonPropertyName("savingsAndGainsIncome")]
        public SavingsAndGainsIncome SavingsAndGainsIncome { get; set; }

        [JsonPropertyName("dividendsIncome")]
        public DividendsIncome DividendsIncome { get; set; }

        [JsonPropertyName("otherIncome")]
        public OtherIncome OtherIncome { get; set; }

        [JsonPropertyName("incomeSummaryTotals")]
        public IncomeSummaryTotals IncomeSummaryTotals { get; set; }

        [JsonPropertyName("taxCalculation")]
        public TaxCalculation TaxCalculation { get; set; }

        [JsonPropertyName("previousCalculation")]
        public PreviousCalculation PreviousCalculation { get; set; }

        [JsonPropertyName("endOfYearEstimate")]
        public EndOfYearEstimate EndOfYearEstimate { get; set; }

        [JsonPropertyName("lossesAndClaims")]
        public LossesAndClaims LossesAndClaims { get; set; }

        [JsonPropertyName("transitionProfit")]
        public TransitionProfit TransitionProfit { get; set; }

        [JsonPropertyName("highIncomeChildBenefitCharge")]
        public HighIncomeChildBenefitCharge HighIncomeChildBenefitCharge { get; set; }
    }

    public partial class AllowancesAndDeductions
    {
        [JsonPropertyName("personalAllowance")]
        public long PersonalAllowance { get; set; }

        [JsonPropertyName("marriageAllowanceTransferOut")]
        public MarriageAllowanceTransferOut MarriageAllowanceTransferOut { get; set; }

        [JsonPropertyName("reducedPersonalAllowance")]
        public long ReducedPersonalAllowance { get; set; }

        [JsonPropertyName("giftOfInvestmentsAndPropertyToCharity")]
        public long GiftOfInvestmentsAndPropertyToCharity { get; set; }

        [JsonPropertyName("blindPersonsAllowance")]
        public long BlindPersonsAllowance { get; set; }

        [JsonPropertyName("lossesAppliedToGeneralIncome")]
        public long LossesAppliedToGeneralIncome { get; set; }

        [JsonPropertyName("cgtLossSetAgainstInYearGeneralIncome")]
        public long CgtLossSetAgainstInYearGeneralIncome { get; set; }

        [JsonPropertyName("qualifyingLoanInterestFromInvestments")]
        public double QualifyingLoanInterestFromInvestments { get; set; }

        [JsonPropertyName("postCessationTradeReceipts")]
        public double PostCessationTradeReceipts { get; set; }

        [JsonPropertyName("paymentsToTradeUnionsForDeathBenefits")]
        public double PaymentsToTradeUnionsForDeathBenefits { get; set; }

        [JsonPropertyName("grossAnnuityPayments")]
        public double GrossAnnuityPayments { get; set; }

        [JsonPropertyName("annuityPayments")]
        public AnnuityPayments AnnuityPayments { get; set; }

        [JsonPropertyName("pensionContributions")]
        public double PensionContributions { get; set; }

        [JsonPropertyName("pensionContributionsDetail")]
        public PensionContributionsDetail PensionContributionsDetail { get; set; }
    }

    public partial class AnnuityPayments
    {
        [JsonPropertyName("reliefClaimed")]
        public double ReliefClaimed { get; set; }

        [JsonPropertyName("rate")]
        public double Rate { get; set; }
    }

    public partial class MarriageAllowanceTransferOut
    {
        [JsonPropertyName("personalAllowanceBeforeTransferOut")]
        public double PersonalAllowanceBeforeTransferOut { get; set; }

        [JsonPropertyName("transferredOutAmount")]
        public double TransferredOutAmount { get; set; }
    }

    public partial class PensionContributionsDetail
    {
        [JsonPropertyName("retirementAnnuityPayments")]
        public double RetirementAnnuityPayments { get; set; }

        [JsonPropertyName("paymentToEmployersSchemeNoTaxRelief")]
        public double PaymentToEmployersSchemeNoTaxRelief { get; set; }

        [JsonPropertyName("overseasPensionSchemeContributions")]
        public double OverseasPensionSchemeContributions { get; set; }
    }

    public partial class BusinessProfitAndLoss
    {
        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("incomeSourceType")]
        public string IncomeSourceType { get; set; }

        [JsonPropertyName("incomeSourceName")]
        public string IncomeSourceName { get; set; }

        [JsonPropertyName("totalIncome")]
        public double TotalIncome { get; set; }

        [JsonPropertyName("totalExpenses")]
        public double TotalExpenses { get; set; }

        [JsonPropertyName("netProfit")]
        public double NetProfit { get; set; }

        [JsonPropertyName("netLoss")]
        public double NetLoss { get; set; }

        [JsonPropertyName("totalAdditions")]
        public double TotalAdditions { get; set; }

        [JsonPropertyName("totalDeductions")]
        public double TotalDeductions { get; set; }

        [JsonPropertyName("accountingAdjustments")]
        public double AccountingAdjustments { get; set; }

        [JsonPropertyName("taxableProfit")]
        public long TaxableProfit { get; set; }

        [JsonPropertyName("adjustedIncomeTaxLoss")]
        public long AdjustedIncomeTaxLoss { get; set; }

        [JsonPropertyName("totalBroughtForwardIncomeTaxLosses")]
        public long TotalBroughtForwardIncomeTaxLosses { get; set; }

        [JsonPropertyName("broughtForwardIncomeTaxLossesUsed")]
        public long BroughtForwardIncomeTaxLossesUsed { get; set; }

        [JsonPropertyName("taxableProfitAfterIncomeTaxLossesDeduction")]
        public long TaxableProfitAfterIncomeTaxLossesDeduction { get; set; }

        [JsonPropertyName("carrySidewaysIncomeTaxLossesUsed")]
        public long CarrySidewaysIncomeTaxLossesUsed { get; set; }

        [JsonPropertyName("broughtForwardCarrySidewaysIncomeTaxLossesUsed")]
        public long BroughtForwardCarrySidewaysIncomeTaxLossesUsed { get; set; }

        [JsonPropertyName("totalIncomeTaxLossesCarriedForward")]
        public long TotalIncomeTaxLossesCarriedForward { get; set; }

        [JsonPropertyName("class4Loss")]
        public long Class4Loss { get; set; }

        [JsonPropertyName("totalBroughtForwardClass4Losses")]
        public long TotalBroughtForwardClass4Losses { get; set; }

        [JsonPropertyName("broughtForwardClass4LossesUsed")]
        public long BroughtForwardClass4LossesUsed { get; set; }

        [JsonPropertyName("carrySidewaysClass4LossesUsed")]
        public long CarrySidewaysClass4LossesUsed { get; set; }

        [JsonPropertyName("totalClass4LossesCarriedForward")]
        public long TotalClass4LossesCarriedForward { get; set; }

        [JsonPropertyName("adjustedProfit")]
        public double AdjustedProfit { get; set; }

        [JsonPropertyName("outstandingBusinessIncome")]
        public double OutstandingBusinessIncome { get; set; }
    }

    public partial class ChargeableEventGainsIncome
    {
        [JsonPropertyName("totalOfAllGains")]
        public long TotalOfAllGains { get; set; }

        [JsonPropertyName("totalGainsWithTaxPaid")]
        public long TotalGainsWithTaxPaid { get; set; }

        [JsonPropertyName("gainsWithTaxPaidDetail")]
        public GainsWithDetail[] GainsWithTaxPaidDetail { get; set; }

        [JsonPropertyName("totalGainsWithNoTaxPaidAndVoidedIsa")]
        public long TotalGainsWithNoTaxPaidAndVoidedIsa { get; set; }

        [JsonPropertyName("gainsWithNoTaxPaidAndVoidedIsaDetail")]
        public GainsWithDetail[] GainsWithNoTaxPaidAndVoidedIsaDetail { get; set; }

        [JsonPropertyName("totalForeignGainsOnLifePoliciesTaxPaid")]
        public long TotalForeignGainsOnLifePoliciesTaxPaid { get; set; }

        [JsonPropertyName("foreignGainsOnLifePoliciesTaxPaidDetail")]
        public ForeignGainsOnLifePoliciesTaxPaidDetail[] ForeignGainsOnLifePoliciesTaxPaidDetail { get; set; }

        [JsonPropertyName("totalForeignGainsOnLifePoliciesNoTaxPaid")]
        public long TotalForeignGainsOnLifePoliciesNoTaxPaid { get; set; }

        [JsonPropertyName("foreignGainsOnLifePoliciesNoTaxPaidDetail")]
        public ForeignGainsOnLifePoliciesTaxPaidDetail[] ForeignGainsOnLifePoliciesNoTaxPaidDetail { get; set; }
    }

    public partial class ForeignGainsOnLifePoliciesTaxPaidDetail
    {
        [JsonPropertyName("customerReference")]
        public string CustomerReference { get; set; }

        [JsonPropertyName("gainAmount")]
        public double GainAmount { get; set; }

        [JsonPropertyName("yearsHeld")]
        public long YearsHeld { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("taxPaidAmount")]
        public double? TaxPaidAmount { get; set; }
    }

    public partial class GainsWithDetail
    {
        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonPropertyName("customerReference")]
        public string CustomerReference { get; set; }

        [JsonPropertyName("gainAmount")]
        public double GainAmount { get; set; }

        [JsonPropertyName("yearsHeld")]
        public long YearsHeld { get; set; }

        [JsonPropertyName("yearsHeldSinceLastGain")]
        public long YearsHeldSinceLastGain { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("voidedIsaTaxPaid")]
        public double? VoidedIsaTaxPaid { get; set; }
    }

    public partial class CodedOutUnderpayments
    {
        [JsonPropertyName("totalPayeUnderpayments")]
        public double TotalPayeUnderpayments { get; set; }

        [JsonPropertyName("payeUnderpaymentsDetail")]
        public PayeUnderpaymentsDetail[] PayeUnderpaymentsDetail { get; set; }

        [JsonPropertyName("totalSelfAssessmentUnderpayments")]
        public double TotalSelfAssessmentUnderpayments { get; set; }

        [JsonPropertyName("totalCollectedSelfAssessmentUnderpayments")]
        public double TotalCollectedSelfAssessmentUnderpayments { get; set; }

        [JsonPropertyName("totalUncollectedSelfAssessmentUnderpayments")]
        public double TotalUncollectedSelfAssessmentUnderpayments { get; set; }

        [JsonPropertyName("selfAssessmentUnderpaymentsDetail")]
        public SelfAssessmentUnderpaymentsDetail[] SelfAssessmentUnderpaymentsDetail { get; set; }
    }

    public partial class PayeUnderpaymentsDetail
    {
        [JsonPropertyName("amount")]
        public double Amount { get; set; }

        [JsonPropertyName("relatedTaxYear")]
        public string RelatedTaxYear { get; set; }

        [JsonPropertyName("source")]
        public string Source { get; set; }
    }

    public partial class SelfAssessmentUnderpaymentsDetail
    {
        [JsonPropertyName("amount")]
        public double Amount { get; set; }

        [JsonPropertyName("relatedTaxYear")]
        public string RelatedTaxYear { get; set; }

        [JsonPropertyName("source")]
        public string Source { get; set; }

        [JsonPropertyName("collectedAmount")]
        public double CollectedAmount { get; set; }

        [JsonPropertyName("uncollectedAmount")]
        public double UncollectedAmount { get; set; }
    }

    public partial class DividendsIncome
    {
        [JsonPropertyName("totalChargeableDividends")]
        public long TotalChargeableDividends { get; set; }

        [JsonPropertyName("totalUkDividends")]
        public long TotalUkDividends { get; set; }

        [JsonPropertyName("ukDividends")]
        public UkDividends UkDividends { get; set; }

        [JsonPropertyName("otherDividends")]
        public OtherDividend[] OtherDividends { get; set; }

        [JsonPropertyName("chargeableForeignDividends")]
        public long ChargeableForeignDividends { get; set; }

        [JsonPropertyName("foreignDividends")]
        public DividendIncomeReceivedWhilstAbroad[] ForeignDividends { get; set; }

        [JsonPropertyName("dividendIncomeReceivedWhilstAbroad")]
        public DividendIncomeReceivedWhilstAbroad[] DividendIncomeReceivedWhilstAbroad { get; set; }
    }

    public partial class DividendIncomeReceivedWhilstAbroad
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("incomeSourceType")]
        public string? IncomeSourceType { get; set; }

        [JsonPropertyName("countryCode")]
        public string CountryCode { get; set; }

        [JsonPropertyName("grossIncome")]
        public double GrossIncome { get; set; }

        [JsonPropertyName("netIncome")]
        public double NetIncome { get; set; }

        [JsonPropertyName("taxDeducted")]
        public double TaxDeducted { get; set; }

        [JsonPropertyName("foreignTaxCreditRelief")]
        public bool ForeignTaxCreditRelief { get; set; }
    }

    public partial class OtherDividend
    {
        [JsonPropertyName("typeOfDividend")]
        public string TypeOfDividend { get; set; }

        [JsonPropertyName("customerReference")]
        public string CustomerReference { get; set; }

        [JsonPropertyName("grossAmount")]
        public double GrossAmount { get; set; }
    }

    public partial class UkDividends
    {
        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("incomeSourceType")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long IncomeSourceType { get; set; }

        [JsonPropertyName("dividends")]
        public long Dividends { get; set; }

        [JsonPropertyName("otherUkDividends")]
        public long OtherUkDividends { get; set; }
    }

    public partial class EmploymentAndPensionsIncome
    {
        [JsonPropertyName("totalPayeEmploymentAndLumpSumIncome")]
        public double TotalPayeEmploymentAndLumpSumIncome { get; set; }

        [JsonPropertyName("totalOccupationalPensionIncome")]
        public double TotalOccupationalPensionIncome { get; set; }

        [JsonPropertyName("totalBenefitsInKind")]
        public double TotalBenefitsInKind { get; set; }

        [JsonPropertyName("tipsIncome")]
        public double TipsIncome { get; set; }

        [JsonPropertyName("employmentAndPensionsIncomeDetail")]
        public EmploymentAndPensionsIncomeDetail[] EmploymentAndPensionsIncomeDetail { get; set; }
    }

    public partial class EmploymentAndPensionsIncomeDetail
    {
        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("source")]
        public string Source { get; set; }

        [JsonPropertyName("occupationalPension")]
        public bool OccupationalPension { get; set; }

        [JsonPropertyName("employerRef")]
        public string EmployerRef { get; set; }

        [JsonPropertyName("employerName")]
        public string EmployerName { get; set; }

        [JsonPropertyName("payrollId")]
        public string PayrollId { get; set; }

        [JsonPropertyName("offPayrollWorker")]
        public bool OffPayrollWorker { get; set; }

        [JsonPropertyName("startDate")]
        public DateTimeOffset StartDate { get; set; }

        [JsonPropertyName("dateEmploymentEnded")]
        public DateTimeOffset DateEmploymentEnded { get; set; }

        [JsonPropertyName("taxablePayToDate")]
        public double TaxablePayToDate { get; set; }

        [JsonPropertyName("totalTaxToDate")]
        public double TotalTaxToDate { get; set; }

        [JsonPropertyName("disguisedRemuneration")]
        public bool DisguisedRemuneration { get; set; }

        [JsonPropertyName("lumpSums")]
        public LumpSums LumpSums { get; set; }

        [JsonPropertyName("studentLoans")]
        public StudentLoans StudentLoans { get; set; }

        [JsonPropertyName("benefitsInKind")]
        public BenefitsInKind BenefitsInKind { get; set; }
    }

    public partial class BenefitsInKind
    {
        [JsonPropertyName("totalBenefitsInKindReceived")]
        public double TotalBenefitsInKindReceived { get; set; }

        [JsonPropertyName("benefitsInKindDetail")]
        public Dictionary<string, double> BenefitsInKindDetail { get; set; }
    }

    public partial class LumpSums
    {
        [JsonPropertyName("totalLumpSum")]
        public double TotalLumpSum { get; set; }

        [JsonPropertyName("totalTaxPaid")]
        public double TotalTaxPaid { get; set; }

        [JsonPropertyName("lumpSumsDetail")]
        public LumpSumsDetail LumpSumsDetail { get; set; }
    }

    public partial class LumpSumsDetail
    {
        [JsonPropertyName("taxableLumpSumsAndCertainIncome")]
        public BenefitFromEmployerFinancedRetirementScheme TaxableLumpSumsAndCertainIncome { get; set; }

        [JsonPropertyName("benefitFromEmployerFinancedRetirementScheme")]
        public BenefitFromEmployerFinancedRetirementScheme BenefitFromEmployerFinancedRetirementScheme { get; set; }

        [JsonPropertyName("redundancyCompensationPaymentsOverExemption")]
        public BenefitFromEmployerFinancedRetirementScheme RedundancyCompensationPaymentsOverExemption { get; set; }

        [JsonPropertyName("redundancyCompensationPaymentsUnderExemption")]
        public GiftAidTaxReductionWhereBasicRateDiffers RedundancyCompensationPaymentsUnderExemption { get; set; }
    }

    public partial class BenefitFromEmployerFinancedRetirementScheme
    {
        [JsonPropertyName("amount")]
        public double Amount { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("exemptAmount")]
        public double? ExemptAmount { get; set; }

        [JsonPropertyName("taxPaid")]
        public double TaxPaid { get; set; }

        [JsonPropertyName("taxTakenOffInEmployment")]
        public bool TaxTakenOffInEmployment { get; set; }
    }

    public partial class GiftAidTaxReductionWhereBasicRateDiffers
    {
        [JsonPropertyName("amount")]
        public double Amount { get; set; }
    }

    public partial class StudentLoans
    {
        [JsonPropertyName("uglDeductionAmount")]
        public double UglDeductionAmount { get; set; }

        [JsonPropertyName("pglDeductionAmount")]
        public double PglDeductionAmount { get; set; }
    }

    public partial class EmploymentExpenses
    {
        [JsonPropertyName("totalEmploymentExpenses")]
        public double TotalEmploymentExpenses { get; set; }

        [JsonPropertyName("employmentExpensesDetail")]
        public EmploymentExpensesDetail EmploymentExpensesDetail { get; set; }
    }

    public partial class EmploymentExpensesDetail
    {
        [JsonPropertyName("businessTravelCosts")]
        public double BusinessTravelCosts { get; set; }

        [JsonPropertyName("jobExpenses")]
        public double JobExpenses { get; set; }

        [JsonPropertyName("flatRateJobExpenses")]
        public double FlatRateJobExpenses { get; set; }

        [JsonPropertyName("professionalSubscriptions")]
        public double ProfessionalSubscriptions { get; set; }

        [JsonPropertyName("hotelAndMealExpenses")]
        public double HotelAndMealExpenses { get; set; }

        [JsonPropertyName("otherAndCapitalAllowances")]
        public double OtherAndCapitalAllowances { get; set; }

        [JsonPropertyName("vehicleExpenses")]
        public double VehicleExpenses { get; set; }

        [JsonPropertyName("mileageAllowanceRelief")]
        public double MileageAllowanceRelief { get; set; }
    }

    public partial class EndOfYearEstimate
    {
        [JsonPropertyName("incomeSource")]
        public IncomeSource[] IncomeSource { get; set; }

        [JsonPropertyName("totalEstimatedIncome")]
        public long TotalEstimatedIncome { get; set; }

        [JsonPropertyName("totalAllowancesAndDeductions")]
        public long TotalAllowancesAndDeductions { get; set; }

        [JsonPropertyName("totalTaxableIncome")]
        public long TotalTaxableIncome { get; set; }

        [JsonPropertyName("incomeTaxAmount")]
        public double IncomeTaxAmount { get; set; }

        [JsonPropertyName("nic2")]
        public double Nic2 { get; set; }

        [JsonPropertyName("nic4")]
        public double Nic4 { get; set; }

        [JsonPropertyName("totalNicAmount")]
        public double TotalNicAmount { get; set; }

        [JsonPropertyName("totalTaxDeductedBeforeCodingOut")]
        public double TotalTaxDeductedBeforeCodingOut { get; set; }

        [JsonPropertyName("saUnderpaymentsCodedOut")]
        public double SaUnderpaymentsCodedOut { get; set; }

        [JsonPropertyName("totalStudentLoansRepaymentAmount")]
        public double TotalStudentLoansRepaymentAmount { get; set; }

        [JsonPropertyName("totalAnnuityPaymentsTaxCharged")]
        public double TotalAnnuityPaymentsTaxCharged { get; set; }

        [JsonPropertyName("totalRoyaltyPaymentsTaxCharged")]
        public double TotalRoyaltyPaymentsTaxCharged { get; set; }

        [JsonPropertyName("totalTaxDeducted")]
        public double TotalTaxDeducted { get; set; }

        [JsonPropertyName("incomeTaxNicAmount")]
        public double IncomeTaxNicAmount { get; set; }

        [JsonPropertyName("cgtAmount")]
        public double CgtAmount { get; set; }

        [JsonPropertyName("incomeTaxNicAndCgtAmount")]
        public double IncomeTaxNicAndCgtAmount { get; set; }
    }

    public partial class IncomeSource
    {
        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("incomeSourceType")]
        public string IncomeSourceType { get; set; }

        [JsonPropertyName("incomeSourceName")]
        public string IncomeSourceName { get; set; }

        [JsonPropertyName("taxableIncome")]
        public long TaxableIncome { get; set; }
    }

    public partial class ForeignIncome
    {
        [JsonPropertyName("chargeableOverseasPensionsStateBenefitsRoyalties")]
        public double ChargeableOverseasPensionsStateBenefitsRoyalties { get; set; }

        [JsonPropertyName("overseasPensionsStateBenefitsRoyaltiesDetail")]
        public DividendIncomeReceivedWhilstAbroad[] OverseasPensionsStateBenefitsRoyaltiesDetail { get; set; }

        [JsonPropertyName("chargeableAllOtherIncomeReceivedWhilstAbroad")]
        public double ChargeableAllOtherIncomeReceivedWhilstAbroad { get; set; }

        [JsonPropertyName("allOtherIncomeReceivedWhilstAbroadDetail")]
        public DividendIncomeReceivedWhilstAbroad[] AllOtherIncomeReceivedWhilstAbroadDetail { get; set; }

        [JsonPropertyName("overseasIncomeAndGains")]
        public OverseasIncomeAndGains OverseasIncomeAndGains { get; set; }

        [JsonPropertyName("totalForeignBenefitsAndGifts")]
        public double TotalForeignBenefitsAndGifts { get; set; }

        [JsonPropertyName("chargeableForeignBenefitsAndGiftsDetail")]
        public ChargeableForeignBenefitsAndGiftsDetail ChargeableForeignBenefitsAndGiftsDetail { get; set; }
    }

    public partial class ChargeableForeignBenefitsAndGiftsDetail
    {
        [JsonPropertyName("transactionBenefit")]
        public double TransactionBenefit { get; set; }

        [JsonPropertyName("protectedForeignIncomeSourceBenefit")]
        public double ProtectedForeignIncomeSourceBenefit { get; set; }

        [JsonPropertyName("protectedForeignIncomeOnwardGift")]
        public double ProtectedForeignIncomeOnwardGift { get; set; }

        [JsonPropertyName("benefitReceivedAsASettler")]
        public double BenefitReceivedAsASettler { get; set; }

        [JsonPropertyName("onwardGiftReceivedAsASettler")]
        public double OnwardGiftReceivedAsASettler { get; set; }
    }

    public partial class OverseasIncomeAndGains
    {
        [JsonPropertyName("gainAmount")]
        public double GainAmount { get; set; }
    }

    public partial class ForeignPropertyIncome
    {
        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("incomeSourceType")]
        public string IncomeSourceType { get; set; }

        [JsonPropertyName("countryCode")]
        public string CountryCode { get; set; }

        [JsonPropertyName("totalIncome")]
        public double TotalIncome { get; set; }

        [JsonPropertyName("totalExpenses")]
        public double TotalExpenses { get; set; }

        [JsonPropertyName("netProfit")]
        public double NetProfit { get; set; }

        [JsonPropertyName("netLoss")]
        public double NetLoss { get; set; }

        [JsonPropertyName("totalAdditions")]
        public double TotalAdditions { get; set; }

        [JsonPropertyName("totalDeductions")]
        public double TotalDeductions { get; set; }

        [JsonPropertyName("taxableProfit")]
        public double TaxableProfit { get; set; }

        [JsonPropertyName("adjustedIncomeTaxLoss")]
        public double AdjustedIncomeTaxLoss { get; set; }
    }

    public partial class ForeignTaxForFtcrNotClaimed
    {
        [JsonPropertyName("foreignTaxOnForeignEmployment")]
        public double ForeignTaxOnForeignEmployment { get; set; }
    }

    public partial class GiftAid
    {
        [JsonPropertyName("grossGiftAidPayments")]
        public long GrossGiftAidPayments { get; set; }

        [JsonPropertyName("rate")]
        public long Rate { get; set; }

        [JsonPropertyName("giftAidTax")]
        public double GiftAidTax { get; set; }

        [JsonPropertyName("giftAidTaxReductions")]
        public double GiftAidTaxReductions { get; set; }

        [JsonPropertyName("incomeTaxChargedAfterGiftAidTaxReductions")]
        public double IncomeTaxChargedAfterGiftAidTaxReductions { get; set; }

        [JsonPropertyName("giftAidCharge")]
        public double GiftAidCharge { get; set; }
    }

    public partial class HighIncomeChildBenefitCharge
    {
        [JsonPropertyName("adjustedNetIncome")]
        public double AdjustedNetIncome { get; set; }

        [JsonPropertyName("amountOfChildBenefitReceived")]
        public double AmountOfChildBenefitReceived { get; set; }

        [JsonPropertyName("incomeThreshold")]
        public long IncomeThreshold { get; set; }

        [JsonPropertyName("childBenefitChargeTaper")]
        public long ChildBenefitChargeTaper { get; set; }

        [JsonPropertyName("rate")]
        public double Rate { get; set; }

        [JsonPropertyName("highIncomeBenefitCharge")]
        public double HighIncomeBenefitCharge { get; set; }
    }

    public partial class IncomeSummaryTotals
    {
        [JsonPropertyName("totalSelfEmploymentProfit")]
        public long TotalSelfEmploymentProfit { get; set; }

        [JsonPropertyName("totalUKPropertyProfit")]
        public long TotalUkPropertyProfit { get; set; }

        [JsonPropertyName("totalForeignPropertyProfit")]
        public long TotalForeignPropertyProfit { get; set; }

        [JsonPropertyName("totalEmploymentIncome")]
        public long TotalEmploymentIncome { get; set; }
    }

    public partial class LossesAndClaims
    {
        [JsonPropertyName("resultOfClaimsApplied")]
        public ResultOfClaimsApplied[] ResultOfClaimsApplied { get; set; }

        [JsonPropertyName("unclaimedLosses")]
        public DLoss[] UnclaimedLosses { get; set; }

        [JsonPropertyName("carriedForwardLosses")]
        public CarriedForwardLoss[] CarriedForwardLosses { get; set; }

        [JsonPropertyName("defaultCarriedForwardLosses")]
        public DLoss[] DefaultCarriedForwardLosses { get; set; }

        [JsonPropertyName("claimsNotApplied")]
        public ClaimsNotApplied[] ClaimsNotApplied { get; set; }
    }

    public partial class CarriedForwardLoss
    {
        [JsonPropertyName("claimId")]
        public string ClaimId { get; set; }

        [JsonPropertyName("originatingClaimId")]
        public string OriginatingClaimId { get; set; }

        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("incomeSourceType")]
        public string IncomeSourceType { get; set; }

        [JsonPropertyName("claimType")]
        public string ClaimType { get; set; }

        [JsonPropertyName("taxYearClaimMade")]
        public string TaxYearClaimMade { get; set; }

        [JsonPropertyName("taxYearLossIncurred")]
        public string TaxYearLossIncurred { get; set; }

        [JsonPropertyName("currentLossValue")]
        public long CurrentLossValue { get; set; }

        [JsonPropertyName("lossType")]
        public string LossType { get; set; }
    }

    public partial class ClaimsNotApplied
    {
        [JsonPropertyName("claimId")]
        public string ClaimId { get; set; }

        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("incomeSourceType")]
        public string IncomeSourceType { get; set; }

        [JsonPropertyName("taxYearClaimMade")]
        public string TaxYearClaimMade { get; set; }

        [JsonPropertyName("claimType")]
        public string ClaimType { get; set; }
    }

    public partial class DLoss
    {
        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("incomeSourceType")]
        public string IncomeSourceType { get; set; }

        [JsonPropertyName("taxYearLossIncurred")]
        public string TaxYearLossIncurred { get; set; }

        [JsonPropertyName("currentLossValue")]
        public long CurrentLossValue { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("lossType")]
        public string? LossType { get; set; }
    }

    public partial class ResultOfClaimsApplied
    {
        [JsonPropertyName("claimId")]
        public string ClaimId { get; set; }

        [JsonPropertyName("originatingClaimId")]
        public string OriginatingClaimId { get; set; }

        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("incomeSourceType")]
        public string IncomeSourceType { get; set; }

        [JsonPropertyName("taxYearClaimMade")]
        public string TaxYearClaimMade { get; set; }

        [JsonPropertyName("claimType")]
        public string ClaimType { get; set; }

        [JsonPropertyName("mtdLoss")]
        public bool MtdLoss { get; set; }

        [JsonPropertyName("taxYearLossIncurred")]
        public string TaxYearLossIncurred { get; set; }

        [JsonPropertyName("lossAmountUsed")]
        public long LossAmountUsed { get; set; }

        [JsonPropertyName("remainingLossValue")]
        public long RemainingLossValue { get; set; }

        [JsonPropertyName("lossType")]
        public string LossType { get; set; }
    }

    public partial class MarriageAllowanceTransferredIn
    {
        [JsonPropertyName("amount")]
        public double Amount { get; set; }

        [JsonPropertyName("rate")]
        public long Rate { get; set; }
    }

    public partial class NotionalTax
    {
        [JsonPropertyName("chargeableGains")]
        public double ChargeableGains { get; set; }
    }

    public partial class OtherIncome
    {
        [JsonPropertyName("totalOtherIncome")]
        public double TotalOtherIncome { get; set; }

        [JsonPropertyName("postCessationIncome")]
        public PostCessationIncome PostCessationIncome { get; set; }
    }

    public partial class PostCessationIncome
    {
        [JsonPropertyName("totalPostCessationReceipts")]
        public double TotalPostCessationReceipts { get; set; }

        [JsonPropertyName("postCessationReceipts")]
        public PostCessationReceipt[] PostCessationReceipts { get; set; }
    }

    public partial class PostCessationReceipt
    {
        [JsonPropertyName("amount")]
        public double Amount { get; set; }

        [JsonPropertyName("taxYearIncomeToBeTaxed")]
        public string TaxYearIncomeToBeTaxed { get; set; }
    }

    public partial class PensionContributionReliefs
    {
        [JsonPropertyName("totalPensionContributionReliefs")]
        public double TotalPensionContributionReliefs { get; set; }

        [JsonPropertyName("pensionContributionDetail")]
        public PensionContributionDetail PensionContributionDetail { get; set; }
    }

    public partial class PensionContributionDetail
    {
        [JsonPropertyName("regularPensionContributions")]
        public double RegularPensionContributions { get; set; }

        [JsonPropertyName("oneOffPensionContributionsPaid")]
        public double OneOffPensionContributionsPaid { get; set; }
    }

    public partial class PensionSavingsTaxCharges
    {
        [JsonPropertyName("totalPensionCharges")]
        public double TotalPensionCharges { get; set; }

        [JsonPropertyName("totalTaxPaid")]
        public double TotalTaxPaid { get; set; }

        [JsonPropertyName("totalPensionChargesDue")]
        public double TotalPensionChargesDue { get; set; }

        [JsonPropertyName("pensionSavingsTaxChargesDetail")]
        public PensionSavingsTaxChargesDetail PensionSavingsTaxChargesDetail { get; set; }
    }

    public partial class PensionSavingsTaxChargesDetail
    {
        [JsonPropertyName("excessOfLifeTimeAllowance")]
        public ExcessOfLifeTimeAllowance ExcessOfLifeTimeAllowance { get; set; }

        [JsonPropertyName("pensionSchemeUnauthorisedPayments")]
        public PensionSchemeUnauthorisedPayments PensionSchemeUnauthorisedPayments { get; set; }

        [JsonPropertyName("pensionSchemeOverseasTransfers")]
        public PensionSchemeOverseasTransfers PensionSchemeOverseasTransfers { get; set; }

        [JsonPropertyName("pensionContributionsInExcessOfTheAnnualAllowance")]
        public PensionContributionsInExcessOfTheAnnualAllowance PensionContributionsInExcessOfTheAnnualAllowance { get; set; }

        [JsonPropertyName("overseasPensionContributions")]
        public OverseasPensionContributions OverseasPensionContributions { get; set; }
    }

    public partial class ExcessOfLifeTimeAllowance
    {
        [JsonPropertyName("totalChargeableAmount")]
        public double TotalChargeableAmount { get; set; }

        [JsonPropertyName("totalTaxPaid")]
        public double TotalTaxPaid { get; set; }

        [JsonPropertyName("lumpSumBenefitTakenInExcessOfLifetimeAllowance")]
        public BenefitInExcessOfLifetimeAllowance LumpSumBenefitTakenInExcessOfLifetimeAllowance { get; set; }

        [JsonPropertyName("benefitInExcessOfLifetimeAllowance")]
        public BenefitInExcessOfLifetimeAllowance BenefitInExcessOfLifetimeAllowance { get; set; }
    }

    public partial class BenefitInExcessOfLifetimeAllowance
    {
        [JsonPropertyName("amount")]
        public double Amount { get; set; }

        [JsonPropertyName("taxPaid")]
        public double TaxPaid { get; set; }

        [JsonPropertyName("rate")]
        public long Rate { get; set; }

        [JsonPropertyName("chargeableAmount")]
        public double ChargeableAmount { get; set; }
    }

    public partial class OverseasPensionContributions
    {
        [JsonPropertyName("totalShortServiceRefund")]
        public double TotalShortServiceRefund { get; set; }

        [JsonPropertyName("totalShortServiceRefundCharge")]
        public double TotalShortServiceRefundCharge { get; set; }

        [JsonPropertyName("shortServiceRefundTaxPaid")]
        public double ShortServiceRefundTaxPaid { get; set; }

        [JsonPropertyName("totalShortServiceRefundChargeDue")]
        public double TotalShortServiceRefundChargeDue { get; set; }

        [JsonPropertyName("shortServiceRefundBands")]
        public ShortServiceRefundBand[] ShortServiceRefundBands { get; set; }
    }

    public partial class ShortServiceRefundBand
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("rate")]
        public long Rate { get; set; }

        [JsonPropertyName("bandLimit")]
        public long BandLimit { get; set; }

        [JsonPropertyName("apportionedBandLimit")]
        public long ApportionedBandLimit { get; set; }

        [JsonPropertyName("shortServiceRefundAmount")]
        public double ShortServiceRefundAmount { get; set; }

        [JsonPropertyName("shortServiceRefundCharge")]
        public double ShortServiceRefundCharge { get; set; }
    }

    public partial class PensionContributionsInExcessOfTheAnnualAllowance
    {
        [JsonPropertyName("totalContributions")]
        public double TotalContributions { get; set; }

        [JsonPropertyName("totalPensionCharge")]
        public double TotalPensionCharge { get; set; }

        [JsonPropertyName("annualAllowanceTaxPaid")]
        public double AnnualAllowanceTaxPaid { get; set; }

        [JsonPropertyName("totalPensionChargeDue")]
        public double TotalPensionChargeDue { get; set; }

        [JsonPropertyName("pensionBands")]
        public PensionBand[] PensionBands { get; set; }
    }

    public partial class PensionBand
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("rate")]
        public long Rate { get; set; }

        [JsonPropertyName("bandLimit")]
        public long BandLimit { get; set; }

        [JsonPropertyName("apportionedBandLimit")]
        public long ApportionedBandLimit { get; set; }

        [JsonPropertyName("contributionAmount")]
        public double ContributionAmount { get; set; }

        [JsonPropertyName("pensionCharge")]
        public double PensionCharge { get; set; }
    }

    public partial class PensionSchemeOverseasTransfers
    {
        [JsonPropertyName("transferCharge")]
        public double TransferCharge { get; set; }

        [JsonPropertyName("transferChargeTaxPaid")]
        public double TransferChargeTaxPaid { get; set; }

        [JsonPropertyName("rate")]
        public long Rate { get; set; }

        [JsonPropertyName("chargeableAmount")]
        public double ChargeableAmount { get; set; }
    }

    public partial class PensionSchemeUnauthorisedPayments
    {
        [JsonPropertyName("totalChargeableAmount")]
        public double TotalChargeableAmount { get; set; }

        [JsonPropertyName("totalTaxPaid")]
        public double TotalTaxPaid { get; set; }

        [JsonPropertyName("pensionSchemeUnauthorisedPaymentsSurcharge")]
        public BenefitInExcessOfLifetimeAllowance PensionSchemeUnauthorisedPaymentsSurcharge { get; set; }

        [JsonPropertyName("pensionSchemeUnauthorisedPaymentsNonSurcharge")]
        public BenefitInExcessOfLifetimeAllowance PensionSchemeUnauthorisedPaymentsNonSurcharge { get; set; }
    }

    public partial class PreviousCalculation
    {
        [JsonPropertyName("calculationTimestamp")]
        public DateTimeOffset CalculationTimestamp { get; set; }

        [JsonPropertyName("calculationId")]
        public Guid CalculationId { get; set; }

        [JsonPropertyName("totalIncomeTaxAndNicsDue")]
        public double TotalIncomeTaxAndNicsDue { get; set; }

        [JsonPropertyName("cgtTaxDue")]
        public double CgtTaxDue { get; set; }

        [JsonPropertyName("totalIncomeTaxAndNicsAndCgtDue")]
        public double TotalIncomeTaxAndNicsAndCgtDue { get; set; }

        [JsonPropertyName("incomeTaxNicDueThisPeriod")]
        public double IncomeTaxNicDueThisPeriod { get; set; }

        [JsonPropertyName("cgtDueThisPeriod")]
        public double CgtDueThisPeriod { get; set; }

        [JsonPropertyName("totalIncomeTaxAndNicsAndCgtDueThisPeriod")]
        public double TotalIncomeTaxAndNicsAndCgtDueThisPeriod { get; set; }
    }

    public partial class Reliefs
    {
        [JsonPropertyName("residentialFinanceCosts")]
        public ResidentialFinanceCosts ResidentialFinanceCosts { get; set; }

        [JsonPropertyName("reliefsClaimed")]
        public ReliefsClaimed[] ReliefsClaimed { get; set; }

        [JsonPropertyName("foreignTaxCreditRelief")]
        public ForeignTaxCreditRelief ForeignTaxCreditRelief { get; set; }

        [JsonPropertyName("topSlicingRelief")]
        public GiftAidTaxReductionWhereBasicRateDiffers TopSlicingRelief { get; set; }

        [JsonPropertyName("basicRateExtension")]
        public BasicRateExtension BasicRateExtension { get; set; }

        [JsonPropertyName("giftAidTaxReductionWhereBasicRateDiffers")]
        public GiftAidTaxReductionWhereBasicRateDiffers GiftAidTaxReductionWhereBasicRateDiffers { get; set; }
    }

    public partial class BasicRateExtension
    {
        [JsonPropertyName("totalBasicRateExtension")]
        public double TotalBasicRateExtension { get; set; }

        [JsonPropertyName("giftAidRelief")]
        public long GiftAidRelief { get; set; }

        [JsonPropertyName("pensionContributionReliefs")]
        public double PensionContributionReliefs { get; set; }
    }

    public partial class ForeignTaxCreditRelief
    {
        [JsonPropertyName("customerCalculatedRelief")]
        public bool CustomerCalculatedRelief { get; set; }

        [JsonPropertyName("totalForeignTaxCreditRelief")]
        public double TotalForeignTaxCreditRelief { get; set; }

        [JsonPropertyName("foreignTaxCreditReliefOnProperty")]
        public double ForeignTaxCreditReliefOnProperty { get; set; }

        [JsonPropertyName("foreignTaxCreditReliefOnDividends")]
        public double ForeignTaxCreditReliefOnDividends { get; set; }

        [JsonPropertyName("foreignTaxCreditReliefOnSavings")]
        public double ForeignTaxCreditReliefOnSavings { get; set; }

        [JsonPropertyName("foreignTaxCreditReliefOnForeignIncome")]
        public double ForeignTaxCreditReliefOnForeignIncome { get; set; }

        [JsonPropertyName("foreignTaxCreditReliefDetail")]
        public ForeignTaxCreditReliefDetail[] ForeignTaxCreditReliefDetail { get; set; }
    }

    public partial class ForeignTaxCreditReliefDetail
    {
        [JsonPropertyName("incomeSourceType")]
        public string IncomeSourceType { get; set; }

        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("countryCode")]
        public string CountryCode { get; set; }

        [JsonPropertyName("foreignIncome")]
        public double ForeignIncome { get; set; }

        [JsonPropertyName("foreignTax")]
        public double ForeignTax { get; set; }

        [JsonPropertyName("dtaRate")]
        public long DtaRate { get; set; }

        [JsonPropertyName("dtaAmount")]
        public double DtaAmount { get; set; }

        [JsonPropertyName("ukLiabilityOnIncome")]
        public double UkLiabilityOnIncome { get; set; }

        [JsonPropertyName("foreignTaxCredit")]
        public double ForeignTaxCredit { get; set; }

        [JsonPropertyName("employmentLumpSum")]
        public bool EmploymentLumpSum { get; set; }
    }

    public partial class ReliefsClaimed
    {
        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonPropertyName("amountClaimed")]
        public double AmountClaimed { get; set; }

        [JsonPropertyName("allowableAmount")]
        public double AllowableAmount { get; set; }

        [JsonPropertyName("amountUsed")]
        public double AmountUsed { get; set; }

        [JsonPropertyName("rate")]
        public long Rate { get; set; }

        [JsonPropertyName("reliefsClaimedDetail")]
        public ReliefsClaimedDetail[] ReliefsClaimedDetail { get; set; }
    }

    public partial class ReliefsClaimedDetail
    {
        [JsonPropertyName("amountClaimed")]
        public double AmountClaimed { get; set; }

        [JsonPropertyName("uniqueInvestmentRef")]
        public string UniqueInvestmentRef { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("companyName")]
        public string CompanyName { get; set; }

        [JsonPropertyName("deficiencyReliefType")]
        public string DeficiencyReliefType { get; set; }

        [JsonPropertyName("customerReference")]
        public string CustomerReference { get; set; }
    }

    public partial class ResidentialFinanceCosts
    {
        [JsonPropertyName("adjustedTotalIncome")]
        public double AdjustedTotalIncome { get; set; }

        [JsonPropertyName("totalAllowableAmount")]
        public double TotalAllowableAmount { get; set; }

        [JsonPropertyName("relievableAmount")]
        public double RelievableAmount { get; set; }

        [JsonPropertyName("rate")]
        public long Rate { get; set; }

        [JsonPropertyName("totalResidentialFinanceCostsRelief")]
        public double TotalResidentialFinanceCostsRelief { get; set; }

        [JsonPropertyName("ukProperty")]
        public UkProperty UkProperty { get; set; }

        [JsonPropertyName("foreignProperty")]
        public ForeignProperty ForeignProperty { get; set; }

        [JsonPropertyName("allOtherIncomeReceivedWhilstAbroad")]
        public AllOtherIncomeReceivedWhilstAbroad AllOtherIncomeReceivedWhilstAbroad { get; set; }
    }

    public partial class AllOtherIncomeReceivedWhilstAbroad
    {
        [JsonPropertyName("totalOtherIncomeAllowableAmount")]
        public double TotalOtherIncomeAllowableAmount { get; set; }

        [JsonPropertyName("otherIncomeRfcDetail")]
        public OtherIncomeRfcDetail[] OtherIncomeRfcDetail { get; set; }
    }

    public partial class OtherIncomeRfcDetail
    {
        [JsonPropertyName("countryCode")]
        public string CountryCode { get; set; }

        [JsonPropertyName("residentialFinancialCostAmount")]
        public double ResidentialFinancialCostAmount { get; set; }

        [JsonPropertyName("broughtFwdResidentialFinancialCostAmount")]
        public double BroughtFwdResidentialFinancialCostAmount { get; set; }
    }

    public partial class ForeignProperty
    {
        [JsonPropertyName("totalForeignPropertyAllowableAmount")]
        public double TotalForeignPropertyAllowableAmount { get; set; }

        [JsonPropertyName("foreignPropertyRfcDetail")]
        public UkProperty[] ForeignPropertyRfcDetail { get; set; }
    }

    public partial class UkProperty
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("countryCode")]
        public string? CountryCode { get; set; }

        [JsonPropertyName("amountClaimed")]
        public long AmountClaimed { get; set; }

        [JsonPropertyName("allowableAmount")]
        public double AllowableAmount { get; set; }

        [JsonPropertyName("carryForwardAmount")]
        public double CarryForwardAmount { get; set; }
    }

    public partial class RoyaltyPayments
    {
        [JsonPropertyName("royaltyPaymentsAmount")]
        public long RoyaltyPaymentsAmount { get; set; }

        [JsonPropertyName("rate")]
        public long Rate { get; set; }

        [JsonPropertyName("grossRoyaltyPayments")]
        public long GrossRoyaltyPayments { get; set; }
    }

    public partial class SavingsAndGainsIncome
    {
        [JsonPropertyName("totalChargeableSavingsAndGains")]
        public long TotalChargeableSavingsAndGains { get; set; }

        [JsonPropertyName("totalUkSavingsAndGains")]
        public long TotalUkSavingsAndGains { get; set; }

        [JsonPropertyName("ukSavingsAndGainsIncome")]
        public UkSavingsAndGainsIncome[] UkSavingsAndGainsIncome { get; set; }

        [JsonPropertyName("chargeableForeignSavingsAndGains")]
        public long ChargeableForeignSavingsAndGains { get; set; }

        [JsonPropertyName("foreignSavingsAndGainsIncome")]
        public DividendIncomeReceivedWhilstAbroad[] ForeignSavingsAndGainsIncome { get; set; }
    }

    public partial class UkSavingsAndGainsIncome
    {
        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("incomeSourceType")]
        public string IncomeSourceType { get; set; }

        [JsonPropertyName("incomeSourceName")]
        public string IncomeSourceName { get; set; }

        [JsonPropertyName("grossIncome")]
        public double GrossIncome { get; set; }

        [JsonPropertyName("netIncome")]
        public double NetIncome { get; set; }

        [JsonPropertyName("taxDeducted")]
        public double TaxDeducted { get; set; }
    }

    public partial class SeafarersDeductions
    {
        [JsonPropertyName("totalSeafarersDeduction")]
        public double TotalSeafarersDeduction { get; set; }

        [JsonPropertyName("seafarersDeductionDetail")]
        public SeafarersDeductionDetail[] SeafarersDeductionDetail { get; set; }
    }

    public partial class SeafarersDeductionDetail
    {
        [JsonPropertyName("nameOfShip")]
        public string NameOfShip { get; set; }

        [JsonPropertyName("amountDeducted")]
        public double AmountDeducted { get; set; }
    }

    public partial class ShareSchemesIncome
    {
        [JsonPropertyName("totalIncome")]
        public double TotalIncome { get; set; }

        [JsonPropertyName("shareSchemeDetail")]
        public ShareSchemeDetail[] ShareSchemeDetail { get; set; }
    }

    public partial class ShareSchemeDetail
    {
        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonPropertyName("employerName")]
        public string EmployerName { get; set; }

        [JsonPropertyName("employerRef")]
        public string EmployerRef { get; set; }

        [JsonPropertyName("taxableAmount")]
        public double TaxableAmount { get; set; }
    }

    public partial class StateBenefitsIncome
    {
        [JsonPropertyName("totalStateBenefitsIncome")]
        public double TotalStateBenefitsIncome { get; set; }

        [JsonPropertyName("totalStateBenefitsTaxPaid")]
        public double TotalStateBenefitsTaxPaid { get; set; }

        [JsonPropertyName("totalStateBenefitsIncomeExcStatePensionLumpSum")]
        public double TotalStateBenefitsIncomeExcStatePensionLumpSum { get; set; }

        [JsonPropertyName("stateBenefitsDetail")]
        public StateBenefitsDetail StateBenefitsDetail { get; set; }
    }

    public partial class StateBenefitsDetail
    {
        [JsonPropertyName("incapacityBenefit")]
        public BereavementAllowance[] IncapacityBenefit { get; set; }

        [JsonPropertyName("statePension")]
        public BereavementAllowance[] StatePension { get; set; }

        [JsonPropertyName("statePensionLumpSum")]
        public BereavementAllowance[] StatePensionLumpSum { get; set; }

        [JsonPropertyName("employmentSupportAllowance")]
        public BereavementAllowance[] EmploymentSupportAllowance { get; set; }

        [JsonPropertyName("jobSeekersAllowance")]
        public BereavementAllowance[] JobSeekersAllowance { get; set; }

        [JsonPropertyName("bereavementAllowance")]
        public BereavementAllowance[] BereavementAllowance { get; set; }

        [JsonPropertyName("otherStateBenefits")]
        public BereavementAllowance[] OtherStateBenefits { get; set; }
    }

    public partial class BereavementAllowance
    {
        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("amount")]
        public double Amount { get; set; }

        [JsonPropertyName("source")]
        public string Source { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("taxPaid")]
        public double? TaxPaid { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("rate")]
        public long? Rate { get; set; }
    }

    public partial class StudentLoan
    {
        [JsonPropertyName("planType")]
        public string PlanType { get; set; }

        [JsonPropertyName("studentLoanTotalIncomeAmount")]
        public double StudentLoanTotalIncomeAmount { get; set; }

        [JsonPropertyName("studentLoanChargeableIncomeAmount")]
        public double StudentLoanChargeableIncomeAmount { get; set; }

        [JsonPropertyName("studentLoanRepaymentAmount")]
        public double StudentLoanRepaymentAmount { get; set; }

        [JsonPropertyName("studentLoanDeductionsFromEmployment")]
        public double StudentLoanDeductionsFromEmployment { get; set; }

        [JsonPropertyName("studentLoanRepaymentAmountNetOfDeductions")]
        public double StudentLoanRepaymentAmountNetOfDeductions { get; set; }

        [JsonPropertyName("studentLoanApportionedIncomeThreshold")]
        public long StudentLoanApportionedIncomeThreshold { get; set; }

        [JsonPropertyName("studentLoanRate")]
        public long StudentLoanRate { get; set; }

        [JsonPropertyName("payeIncomeForStudentLoan")]
        public double PayeIncomeForStudentLoan { get; set; }

        [JsonPropertyName("nonPayeIncomeForStudentLoan")]
        public double NonPayeIncomeForStudentLoan { get; set; }
    }

    public partial class TaxCalculation
    {
        [JsonPropertyName("incomeTax")]
        public IncomeTax IncomeTax { get; set; }

        [JsonPropertyName("nics")]
        public Nics Nics { get; set; }

        [JsonPropertyName("totalTaxDeductedBeforeCodingOut")]
        public double TotalTaxDeductedBeforeCodingOut { get; set; }

        [JsonPropertyName("saUnderpaymentsCodedOut")]
        public long SaUnderpaymentsCodedOut { get; set; }

        [JsonPropertyName("totalIncomeTaxNicsCharged")]
        public double TotalIncomeTaxNicsCharged { get; set; }

        [JsonPropertyName("totalStudentLoansRepaymentAmount")]
        public double TotalStudentLoansRepaymentAmount { get; set; }

        [JsonPropertyName("totalAnnuityPaymentsTaxCharged")]
        public double TotalAnnuityPaymentsTaxCharged { get; set; }

        [JsonPropertyName("totalRoyaltyPaymentsTaxCharged")]
        public double TotalRoyaltyPaymentsTaxCharged { get; set; }

        [JsonPropertyName("totalTaxDeducted")]
        public double TotalTaxDeducted { get; set; }

        [JsonPropertyName("totalIncomeTaxAndNicsDue")]
        public double TotalIncomeTaxAndNicsDue { get; set; }

        [JsonPropertyName("capitalGainsTax")]
        public CapitalGainsTax CapitalGainsTax { get; set; }

        [JsonPropertyName("totalIncomeTaxAndNicsAndCgt")]
        public double TotalIncomeTaxAndNicsAndCgt { get; set; }
    }

    public partial class CapitalGainsTax
    {
        [JsonPropertyName("totalCapitalGainsIncome")]
        public double TotalCapitalGainsIncome { get; set; }

        [JsonPropertyName("annualExemptionAmount")]
        public double AnnualExemptionAmount { get; set; }

        [JsonPropertyName("totalTaxableGains")]
        public double TotalTaxableGains { get; set; }

        [JsonPropertyName("businessAssetsDisposalsAndInvestorsRel")]
        public BusinessAssetsDisposalsAndInvestorsRel BusinessAssetsDisposalsAndInvestorsRel { get; set; }

        [JsonPropertyName("residentialPropertyAndCarriedInterest")]
        public BusinessAssetsDisposalsAndInvestorsRel ResidentialPropertyAndCarriedInterest { get; set; }

        [JsonPropertyName("otherGains")]
        public OtherGains OtherGains { get; set; }

        [JsonPropertyName("capitalGainsTaxAmount")]
        public double CapitalGainsTaxAmount { get; set; }

        [JsonPropertyName("adjustments")]
        public double Adjustments { get; set; }

        [JsonPropertyName("adjustedCapitalGainsTax")]
        public double AdjustedCapitalGainsTax { get; set; }

        [JsonPropertyName("foreignTaxCreditRelief")]
        public double ForeignTaxCreditRelief { get; set; }

        [JsonPropertyName("capitalGainsTaxAfterFTCR")]
        public double CapitalGainsTaxAfterFtcr { get; set; }

        [JsonPropertyName("taxOnGainsAlreadyPaid")]
        public double TaxOnGainsAlreadyPaid { get; set; }

        [JsonPropertyName("capitalGainsTaxDue")]
        public double CapitalGainsTaxDue { get; set; }

        [JsonPropertyName("capitalGainsOverpaid")]
        public double CapitalGainsOverpaid { get; set; }
    }

    public partial class BusinessAssetsDisposalsAndInvestorsRel
    {
        [JsonPropertyName("gainsIncome")]
        public double GainsIncome { get; set; }

        [JsonPropertyName("lossesBroughtForward")]
        public double LossesBroughtForward { get; set; }

        [JsonPropertyName("lossesArisingThisYear")]
        public double LossesArisingThisYear { get; set; }

        [JsonPropertyName("gainsAfterLosses")]
        public double GainsAfterLosses { get; set; }

        [JsonPropertyName("annualExemptionAmount")]
        public double AnnualExemptionAmount { get; set; }

        [JsonPropertyName("taxableGains")]
        public double TaxableGains { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("rate")]
        public long? Rate { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("taxAmount")]
        public double? TaxAmount { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("cgtTaxBands")]
        public CgtTaxBand[]? CgtTaxBands { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("totalTaxAmount")]
        public double? TotalTaxAmount { get; set; }
    }

    public partial class CgtTaxBand
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("rate")]
        public long Rate { get; set; }

        [JsonPropertyName("income")]
        public double Income { get; set; }

        [JsonPropertyName("taxAmount")]
        public double TaxAmount { get; set; }
    }

    public partial class OtherGains
    {
        [JsonPropertyName("gainsIncome")]
        public double GainsIncome { get; set; }

        [JsonPropertyName("lossesBroughtForward")]
        public double LossesBroughtForward { get; set; }

        [JsonPropertyName("lossesArisingThisYear")]
        public double LossesArisingThisYear { get; set; }

        [JsonPropertyName("gainsAfterLosses")]
        public double GainsAfterLosses { get; set; }

        [JsonPropertyName("attributedGains")]
        public double AttributedGains { get; set; }

        [JsonPropertyName("netGains")]
        public double NetGains { get; set; }

        [JsonPropertyName("annualExemptionAmount")]
        public double AnnualExemptionAmount { get; set; }

        [JsonPropertyName("taxableGains")]
        public double TaxableGains { get; set; }

        [JsonPropertyName("cgtTaxBands")]
        public CgtTaxBand[] CgtTaxBands { get; set; }

        [JsonPropertyName("totalTaxAmount")]
        public double TotalTaxAmount { get; set; }
    }

    public partial class IncomeTax
    {
        [JsonPropertyName("totalIncomeReceivedFromAllSources")]
        public long TotalIncomeReceivedFromAllSources { get; set; }

        [JsonPropertyName("totalAllowancesAndDeductions")]
        public long TotalAllowancesAndDeductions { get; set; }

        [JsonPropertyName("totalTaxableIncome")]
        public long TotalTaxableIncome { get; set; }

        [JsonPropertyName("payPensionsProfit")]
        public Dividends PayPensionsProfit { get; set; }

        [JsonPropertyName("savingsAndGains")]
        public Dividends SavingsAndGains { get; set; }

        [JsonPropertyName("dividends")]
        public Dividends Dividends { get; set; }

        [JsonPropertyName("lumpSums")]
        public Dividends LumpSums { get; set; }

        [JsonPropertyName("gainsOnLifePolicies")]
        public Dividends GainsOnLifePolicies { get; set; }

        [JsonPropertyName("incomeTaxCharged")]
        public double IncomeTaxCharged { get; set; }

        [JsonPropertyName("incomeTaxChargedOnTransitionProfits")]
        public double IncomeTaxChargedOnTransitionProfits { get; set; }

        [JsonPropertyName("incomeTaxChargedAfterTransitionProfits")]
        public double IncomeTaxChargedAfterTransitionProfits { get; set; }

        [JsonPropertyName("totalReliefs")]
        public double TotalReliefs { get; set; }

        [JsonPropertyName("incomeTaxDueAfterReliefs")]
        public double IncomeTaxDueAfterReliefs { get; set; }

        [JsonPropertyName("totalNotionalTax")]
        public double TotalNotionalTax { get; set; }

        [JsonPropertyName("marriageAllowanceRelief")]
        public double MarriageAllowanceRelief { get; set; }

        [JsonPropertyName("incomeTaxDueAfterTaxReductions")]
        public double IncomeTaxDueAfterTaxReductions { get; set; }

        [JsonPropertyName("incomeTaxDueAfterGiftAid")]
        public double IncomeTaxDueAfterGiftAid { get; set; }

        [JsonPropertyName("giftAidTaxChargeWhereBasicRateDiffers")]
        public double GiftAidTaxChargeWhereBasicRateDiffers { get; set; }

        [JsonPropertyName("totalPensionSavingsTaxCharges")]
        public double TotalPensionSavingsTaxCharges { get; set; }

        [JsonPropertyName("statePensionLumpSumCharges")]
        public double StatePensionLumpSumCharges { get; set; }

        [JsonPropertyName("highIncomeBenefitCharge")]
        public double HighIncomeBenefitCharge { get; set; }

        [JsonPropertyName("payeUnderpaymentsCodedOut")]
        public double PayeUnderpaymentsCodedOut { get; set; }

        [JsonPropertyName("totalIncomeTaxDue")]
        public double TotalIncomeTaxDue { get; set; }
    }

    public partial class Dividends
    {
        [JsonPropertyName("incomeReceived")]
        public long IncomeReceived { get; set; }

        [JsonPropertyName("allowancesAllocated")]
        public long AllowancesAllocated { get; set; }

        [JsonPropertyName("taxableIncome")]
        public long TaxableIncome { get; set; }

        [JsonPropertyName("incomeTaxAmount")]
        public double IncomeTaxAmount { get; set; }

        [JsonPropertyName("taxBands")]
        public TaxBand[] TaxBands { get; set; }
    }

    public partial class TaxBand
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("rate")]
        public long Rate { get; set; }

        [JsonPropertyName("bandLimit")]
        public long BandLimit { get; set; }

        [JsonPropertyName("apportionedBandLimit")]
        public long ApportionedBandLimit { get; set; }

        [JsonPropertyName("income")]
        public long Income { get; set; }

        [JsonPropertyName("taxAmount")]
        public double TaxAmount { get; set; }
    }

    public partial class Nics
    {
        [JsonPropertyName("class2Nics")]
        public Class2Nics Class2Nics { get; set; }

        [JsonPropertyName("class4Nics")]
        public Class4Nics Class4Nics { get; set; }

        [JsonPropertyName("nic2NetOfDeductions")]
        public double Nic2NetOfDeductions { get; set; }

        [JsonPropertyName("nic4NetOfDeductions")]
        public double Nic4NetOfDeductions { get; set; }

        [JsonPropertyName("totalNic")]
        public double TotalNic { get; set; }
    }

    public partial class Class2Nics
    {
        [JsonPropertyName("amount")]
        public double Amount { get; set; }

        [JsonPropertyName("weeklyRate")]
        public double WeeklyRate { get; set; }

        [JsonPropertyName("weeks")]
        public long Weeks { get; set; }

        [JsonPropertyName("limit")]
        public long Limit { get; set; }

        [JsonPropertyName("apportionedLimit")]
        public long ApportionedLimit { get; set; }

        [JsonPropertyName("underSmallProfitThreshold")]
        public bool UnderSmallProfitThreshold { get; set; }

        [JsonPropertyName("underLowerProfitThreshold")]
        public bool UnderLowerProfitThreshold { get; set; }

        [JsonPropertyName("actualClass2Nic")]
        public bool ActualClass2Nic { get; set; }
    }

    public partial class Class4Nics
    {
        [JsonPropertyName("totalIncomeLiableToClass4Charge")]
        public long TotalIncomeLiableToClass4Charge { get; set; }

        [JsonPropertyName("totalClass4LossesAvailable")]
        public long TotalClass4LossesAvailable { get; set; }

        [JsonPropertyName("totalClass4LossesUsed")]
        public long TotalClass4LossesUsed { get; set; }

        [JsonPropertyName("totalClass4LossesCarriedForward")]
        public long TotalClass4LossesCarriedForward { get; set; }

        [JsonPropertyName("totalIncomeChargeableToClass4")]
        public long TotalIncomeChargeableToClass4 { get; set; }

        [JsonPropertyName("totalAmount")]
        public double TotalAmount { get; set; }

        [JsonPropertyName("nic4Bands")]
        public Nic4Band[] Nic4Bands { get; set; }
    }

    public partial class Nic4Band
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("rate")]
        public long Rate { get; set; }

        [JsonPropertyName("threshold")]
        public long Threshold { get; set; }

        [JsonPropertyName("apportionedThreshold")]
        public long ApportionedThreshold { get; set; }

        [JsonPropertyName("income")]
        public long Income { get; set; }

        [JsonPropertyName("amount")]
        public double Amount { get; set; }
    }

    public partial class TransitionProfit
    {
        [JsonPropertyName("totalTaxableTransitionProfit")]
        public long TotalTaxableTransitionProfit { get; set; }

        [JsonPropertyName("transitionProfitDetail")]
        public TransitionProfitDetail[] TransitionProfitDetail { get; set; }
    }

    public partial class TransitionProfitDetail
    {
        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("incomeSourceName")]
        public string IncomeSourceName { get; set; }

        [JsonPropertyName("transitionProfitAmount")]
        public double TransitionProfitAmount { get; set; }

        [JsonPropertyName("transitionProfitAccelerationAmount")]
        public double TransitionProfitAccelerationAmount { get; set; }

        [JsonPropertyName("totalTransitionProfit")]
        public long TotalTransitionProfit { get; set; }

        [JsonPropertyName("remainingBroughtForwardIncomeTaxLosses")]
        public long RemainingBroughtForwardIncomeTaxLosses { get; set; }

        [JsonPropertyName("broughtForwardIncomeTaxLossesUsed")]
        public long BroughtForwardIncomeTaxLossesUsed { get; set; }

        [JsonPropertyName("transitionProfitsAfterIncomeTaxLossDeductions")]
        public long TransitionProfitsAfterIncomeTaxLossDeductions { get; set; }
    }

    public partial class Inputs
    {
        [JsonPropertyName("personalInformation")]
        public PersonalInformation PersonalInformation { get; set; }

        [JsonPropertyName("incomeSources")]
        public IncomeSources IncomeSources { get; set; }

        [JsonPropertyName("annualAdjustments")]
        public AnnualAdjustment[] AnnualAdjustments { get; set; }

        [JsonPropertyName("lossesBroughtForward")]
        public LossesBroughtForward[] LossesBroughtForward { get; set; }

        [JsonPropertyName("claims")]
        public Claim[] Claims { get; set; }

        [JsonPropertyName("constructionIndustryScheme")]
        public ConstructionIndustryScheme[] ConstructionIndustryScheme { get; set; }

        [JsonPropertyName("allowancesReliefsAndDeductions")]
        public AllowancesReliefsAndDeduction[] AllowancesReliefsAndDeductions { get; set; }

        [JsonPropertyName("pensionContributionAndCharges")]
        public AllowancesReliefsAndDeduction[] PensionContributionAndCharges { get; set; }

        [JsonPropertyName("other")]
        public Other[] Other { get; set; }
    }

    public partial class AllowancesReliefsAndDeduction
    {
        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("submittedTimestamp")]
        public DateTimeOffset? SubmittedTimestamp { get; set; }

        [JsonPropertyName("startDate")]
        public DateTimeOffset StartDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset EndDate { get; set; }

        [JsonPropertyName("source")]
        public string Source { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("submissionTimestamp")]
        public DateTimeOffset? SubmissionTimestamp { get; set; }
    }

    public partial class AnnualAdjustment
    {
        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("incomeSourceType")]
        public string IncomeSourceType { get; set; }

        [JsonPropertyName("bsasId")]
        public Guid BsasId { get; set; }

        [JsonPropertyName("receivedDateTime")]
        public DateTimeOffset ReceivedDateTime { get; set; }

        [JsonPropertyName("applied")]
        public bool Applied { get; set; }
    }

    public partial class Claim
    {
        [JsonPropertyName("claimId")]
        public string ClaimId { get; set; }

        [JsonPropertyName("originatingClaimId")]
        public string OriginatingClaimId { get; set; }

        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("incomeSourceType")]
        public string IncomeSourceType { get; set; }

        [JsonPropertyName("submissionTimestamp")]
        public DateTimeOffset SubmissionTimestamp { get; set; }

        [JsonPropertyName("taxYearClaimMade")]
        public string TaxYearClaimMade { get; set; }

        [JsonPropertyName("claimType")]
        public string ClaimType { get; set; }

        [JsonPropertyName("sequence")]
        public long Sequence { get; set; }
    }

    public partial class ConstructionIndustryScheme
    {
        [JsonPropertyName("employerRef")]
        public string EmployerRef { get; set; }

        [JsonPropertyName("contractorName")]
        public string ContractorName { get; set; }

        [JsonPropertyName("periodData")]
        public PeriodDatum[] PeriodData { get; set; }
    }

    public partial class PeriodDatum
    {
        [JsonPropertyName("deductionFromDate")]
        public DateTimeOffset DeductionFromDate { get; set; }

        [JsonPropertyName("deductionToDate")]
        public DateTimeOffset DeductionToDate { get; set; }

        [JsonPropertyName("submissionTimestamp")]
        public DateTimeOffset SubmissionTimestamp { get; set; }

        [JsonPropertyName("source")]
        public string Source { get; set; }

        [JsonPropertyName("deductionAmount")]
        public double DeductionAmount { get; set; }
    }

    public partial class IncomeSources
    {
        [JsonPropertyName("businessIncomeSources")]
        public BusinessIncomeSource[] BusinessIncomeSources { get; set; }

        [JsonPropertyName("nonBusinessIncomeSources")]
        public NonBusinessIncomeSource[] NonBusinessIncomeSources { get; set; }
    }

    public partial class BusinessIncomeSource
    {
        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("incomeSourceType")]
        public string IncomeSourceType { get; set; }

        [JsonPropertyName("incomeSourceName")]
        public string IncomeSourceName { get; set; }

        [JsonPropertyName("accountingPeriodStartDate")]
        public DateTimeOffset AccountingPeriodStartDate { get; set; }

        [JsonPropertyName("accountingPeriodEndDate")]
        public DateTimeOffset AccountingPeriodEndDate { get; set; }

        [JsonPropertyName("source")]
        public string Source { get; set; }

        [JsonPropertyName("commencementDate")]
        public DateTimeOffset CommencementDate { get; set; }

        [JsonPropertyName("cessationDate")]
        public DateTimeOffset CessationDate { get; set; }

        [JsonPropertyName("latestPeriodEndDate")]
        public DateTimeOffset LatestPeriodEndDate { get; set; }

        [JsonPropertyName("latestReceivedDateTime")]
        public DateTimeOffset LatestReceivedDateTime { get; set; }

        [JsonPropertyName("submissionPeriod")]
        public SubmissionPeriod SubmissionPeriod { get; set; }
    }

    public partial class SubmissionPeriod
    {
        [JsonPropertyName("submissionId")]
        public string SubmissionId { get; set; }

        [JsonPropertyName("startDate")]
        public DateTimeOffset StartDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset EndDate { get; set; }

        [JsonPropertyName("receivedDateTime")]
        public DateTimeOffset ReceivedDateTime { get; set; }
    }

    public partial class NonBusinessIncomeSource
    {
        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("incomeSourceType")]
        public string IncomeSourceType { get; set; }

        [JsonPropertyName("incomeSourceName")]
        public string IncomeSourceName { get; set; }

        [JsonPropertyName("startDate")]
        public DateTimeOffset StartDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset EndDate { get; set; }

        [JsonPropertyName("source")]
        public string Source { get; set; }

        [JsonPropertyName("periodId")]
        public string PeriodId { get; set; }

        [JsonPropertyName("latestReceivedDateTime")]
        public DateTimeOffset LatestReceivedDateTime { get; set; }
    }

    public partial class LossesBroughtForward
    {
        [JsonPropertyName("lossId")]
        public string LossId { get; set; }

        [JsonPropertyName("incomeSourceId")]
        public string IncomeSourceId { get; set; }

        [JsonPropertyName("incomeSourceType")]
        public string IncomeSourceType { get; set; }

        [JsonPropertyName("submissionTimestamp")]
        public DateTimeOffset SubmissionTimestamp { get; set; }

        [JsonPropertyName("lossType")]
        public string LossType { get; set; }

        [JsonPropertyName("taxYearLossIncurred")]
        public string TaxYearLossIncurred { get; set; }

        [JsonPropertyName("currentLossValue")]
        public long CurrentLossValue { get; set; }

        [JsonPropertyName("mtdLoss")]
        public bool MtdLoss { get; set; }
    }

    public partial class Other
    {
        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonPropertyName("submittedOn")]
        public DateTimeOffset SubmittedOn { get; set; }
    }

    public partial class PersonalInformation
    {
        [JsonPropertyName("identifier")]
        public string Identifier { get; set; }

        [JsonPropertyName("dateOfBirth")]
        public DateTimeOffset DateOfBirth { get; set; }

        [JsonPropertyName("taxRegime")]
        public string TaxRegime { get; set; }

        [JsonPropertyName("statePensionAgeDate")]
        public DateTimeOffset StatePensionAgeDate { get; set; }

        [JsonPropertyName("studentLoanPlan")]
        public StudentLoanPlan[] StudentLoanPlan { get; set; }

        [JsonPropertyName("class2VoluntaryContributions")]
        public bool Class2VoluntaryContributions { get; set; }

        [JsonPropertyName("marriageAllowance")]
        public string MarriageAllowance { get; set; }

        [JsonPropertyName("uniqueTaxpayerReference")]
        public string UniqueTaxpayerReference { get; set; }

        [JsonPropertyName("itsaStatus")]
        public string ItsaStatus { get; set; }
    }

    public partial class StudentLoanPlan
    {
        [JsonPropertyName("planType")]
        public string PlanType { get; set; }
    }

    public partial class Messages
    {
        [JsonPropertyName("info")]
        public Error[] Info { get; set; }

        [JsonPropertyName("warnings")]
        public Error[] Warnings { get; set; }

        [JsonPropertyName("errors")]
        public Error[] Errors { get; set; }
    }

    public partial class Error
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("text")]
        public string Text { get; set; }
    }

    public partial class Metadata
    {
        [JsonPropertyName("calculationId")]
        public Guid CalculationId { get; set; }

        [JsonPropertyName("taxYear")]
        public string TaxYear { get; set; }

        [JsonPropertyName("requestedBy")]
        public string RequestedBy { get; set; }

        [JsonPropertyName("requestedTimestamp")]
        public DateTimeOffset RequestedTimestamp { get; set; }

        [JsonPropertyName("calculationReason")]
        public string CalculationReason { get; set; }

        [JsonPropertyName("calculationTimestamp")]
        public DateTimeOffset CalculationTimestamp { get; set; }

        [JsonPropertyName("calculationType")]
        public string CalculationType { get; set; }

        [JsonPropertyName("finalisationTimestamp")]
        public DateTimeOffset FinalisationTimestamp { get; set; }

        [JsonPropertyName("confirmationTimestamp")]
        public DateTimeOffset ConfirmationTimestamp { get; set; }

        [JsonPropertyName("periodFrom")]
        public DateTimeOffset PeriodFrom { get; set; }

        [JsonPropertyName("periodTo")]
        public DateTimeOffset PeriodTo { get; set; }
    }

    public partial class CalculationResponse2025
    {
        public static CalculationResponse2025 FromJson(string json) => JsonSerializer.Deserialize<CalculationResponse2025>(json, TradeControl.Tax.UK.Hmrc.Sa.v1_0.Calculations.V8.Wire2025.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this CalculationResponse2025 self) => JsonSerializer.Serialize(self, TradeControl.Tax.UK.Hmrc.Sa.v1_0.Calculations.V8.Wire2025.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    internal class ParseStringConverter : JsonConverter<long>
    {
        public override bool CanConvert(Type t) => t == typeof(long);

        public override long Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void Write(Utf8JsonWriter writer, long value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize(writer, value.ToString(), options);
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
    
    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
                get => _dateTimeStyles;
                set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
                get => _dateTimeFormat ?? string.Empty;
                set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
                get => _culture ?? CultureInfo.CurrentCulture;
                set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
                string text;


                if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                        || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
                {
                        value = value.ToUniversalTime();
                }

                text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

                writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                string? dateText = reader.GetString();

                if (string.IsNullOrEmpty(dateText) == false)
                {
                        if (!string.IsNullOrEmpty(_dateTimeFormat))
                        {
                                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                        }
                        else
                        {
                                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                        }
                }
                else
                {
                        return default(DateTimeOffset);
                }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8602
#pragma warning restore CS8603
