@TaxHub.WebHarness_HostAddress = http://localhost:5151

GET {{TaxHub.WebHarness_HostAddress}}/harness/company/accounts/min-full
Accept: application/json

###
GET {{TaxHub.WebHarness_HostAddress}}/harness/company/accounts/min-full/raw
Accept: application/xhtml+xml

###
GET {{TaxHub.WebHarness_HostAddress}}/harness/company/accounts/std-filleted
Accept: application/json

###
GET {{TaxHub.WebHarness_HostAddress}}/harness/company/accounts/std-filleted/raw
Accept: application/xhtml+xml

###

POST {{TaxHub.WebHarness_HostAddress}}/harness/mtd/micro
Content-Type: application/json

{
  "connectionString": "Server=(localdb)\\MSSQLLocalDB;Database=TradeControl;Trusted_Connection=True;TrustServerCertificate=True",
  "tenantId": "TENANT-001",
  "subjectId": "SUB123",
  "period": "2027-03-31",
  "taxSourceCode": "UK-MTD",
  "environment": "sandbox"
}

###
POST {{TaxHub.WebHarness_HostAddress}}/harness/vat
Content-Type: application/json

{
  "connectionString": "Server=(localdb)\\MSSQLLocalDB;Database=TradeControl;Trusted_Connection=True;TrustServerCertificate=True",
  "tenantId": "TENANT-001",
  "subjectId": "SUB123",
  "period": "2026-06-30",
  "taxSourceCode": "VAT",
  "environment": "sandbox"
}
