// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using TradeControl.Tax.UK.Hmrc.Sa.v1_0.BusinessDetails.V2.Wire.detail;
//
//    var businessDetailWireResponse = BusinessDetailWireResponse.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8602
#pragma warning disable CS8603

namespace TradeControl.Tax.UK.Hmrc.Sa.v1_0.BusinessDetails.V2.Wire.detail
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    public partial class BusinessDetailWireResponse
    {
        [JsonPropertyName("businessId")]
        public string BusinessId { get; set; }

        [JsonPropertyName("typeOfBusiness")]
        public string TypeOfBusiness { get; set; }

        [JsonPropertyName("tradingType")]
        public string TradingType { get; set; }

        [JsonPropertyName("tradingName")]
        public string TradingName { get; set; }

        [JsonPropertyName("yearOfMigration")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long YearOfMigration { get; set; }

        [JsonPropertyName("firstAccountingPeriodStartDate")]
        public DateTimeOffset FirstAccountingPeriodStartDate { get; set; }

        [JsonPropertyName("firstAccountingPeriodEndDate")]
        public DateTimeOffset FirstAccountingPeriodEndDate { get; set; }

        [JsonPropertyName("latencyDetails")]
        public LatencyDetails LatencyDetails { get; set; }

        [JsonPropertyName("accountingPeriods")]
        public AccountingPeriod[] AccountingPeriods { get; set; }

        [JsonPropertyName("quarterlyTypeChoice")]
        public QuarterlyTypeChoice QuarterlyTypeChoice { get; set; }

        [JsonPropertyName("commencementDate")]
        public DateTimeOffset CommencementDate { get; set; }

        [JsonPropertyName("cessationDate")]
        public DateTimeOffset CessationDate { get; set; }

        [JsonPropertyName("businessAddressLineOne")]
        public string BusinessAddressLineOne { get; set; }

        [JsonPropertyName("businessAddressLineTwo")]
        public string BusinessAddressLineTwo { get; set; }

        [JsonPropertyName("businessAddressLineThree")]
        public string BusinessAddressLineThree { get; set; }

        [JsonPropertyName("businessAddressLineFour")]
        public string BusinessAddressLineFour { get; set; }

        [JsonPropertyName("businessAddressPostcode")]
        public string BusinessAddressPostcode { get; set; }

        [JsonPropertyName("businessAddressCountryCode")]
        public string BusinessAddressCountryCode { get; set; }
    }

    public partial class AccountingPeriod
    {
        [JsonPropertyName("start")]
        public DateTimeOffset Start { get; set; }

        [JsonPropertyName("end")]
        public DateTimeOffset End { get; set; }
    }

    public partial class LatencyDetails
    {
        [JsonPropertyName("latencyEndDate")]
        public DateTimeOffset LatencyEndDate { get; set; }

        [JsonPropertyName("taxYear1")]
        public string TaxYear1 { get; set; }

        [JsonPropertyName("latencyIndicator1")]
        public string LatencyIndicator1 { get; set; }

        [JsonPropertyName("taxYear2")]
        public string TaxYear2 { get; set; }

        [JsonPropertyName("latencyIndicator2")]
        public string LatencyIndicator2 { get; set; }
    }

    public partial class QuarterlyTypeChoice
    {
        [JsonPropertyName("quarterlyPeriodType")]
        public string QuarterlyPeriodType { get; set; }

        [JsonPropertyName("taxYearOfChoice")]
        public string TaxYearOfChoice { get; set; }
    }

    public partial class BusinessDetailWireResponse
    {
        public static BusinessDetailWireResponse FromJson(string json) => JsonSerializer.Deserialize<BusinessDetailWireResponse>(json, TradeControl.Tax.UK.Hmrc.Sa.v1_0.BusinessDetails.V2.Wire.detail.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this BusinessDetailWireResponse self) => JsonSerializer.Serialize(self, TradeControl.Tax.UK.Hmrc.Sa.v1_0.BusinessDetails.V2.Wire.detail.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    internal class ParseStringConverter : JsonConverter<long>
    {
        public override bool CanConvert(Type t) => t == typeof(long);

        public override long Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void Write(Utf8JsonWriter writer, long value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize(writer, value.ToString(), options);
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
    
    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
                get => _dateTimeStyles;
                set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
                get => _dateTimeFormat ?? string.Empty;
                set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
                get => _culture ?? CultureInfo.CurrentCulture;
                set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
                string text;


                if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                        || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
                {
                        value = value.ToUniversalTime();
                }

                text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

                writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                string? dateText = reader.GetString();

                if (string.IsNullOrEmpty(dateText) == false)
                {
                        if (!string.IsNullOrEmpty(_dateTimeFormat))
                        {
                                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                        }
                        else
                        {
                                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                        }
                }
                else
                {
                        return default(DateTimeOffset);
                }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8602
#pragma warning restore CS8603
